#!/bin/sh
# vidmod
# Do rapid changes to video files using ffmpeg or other tools.

VERSION='1.1.0'

vidmod_main() {
	scriptpath="$( realpath "$0" )"
	scriptname="$( basename "$scriptpath" )"

	e_args=16

	while getopts 'd:f:ho:v' OPTION
	do
		case "$OPTION" in
			d) outputdir="$OPTARG" ;;
			f) ffmpeg_extra_opts="$OPTARG" ;;
			o) final="$OPTARG" ;;
			h) vidmod_help && return ;;
			v) vidmod_version && return ;;
			*) vidmod_help && return $e_args ;;
		esac
	done

	[ $# -gt 0 ] && shift "$(( OPTIND - 1 ))"

	[ $# -lt 2 ] && "${scriptname}_help" && return 1

	for input; do true; done

	[ -z "$outputdir" ] && outputdir="$( dirname "$input" )"
	[ -n "$final" ] && outputdir="$( mktemp -dt ".$scriptname" )"

	ffmpeg_opts="-hide_banner -loglevel panic -nostdin $ffmpeg_extra_opts"

	if [ ! -f "$input" ]
	then
		_error "File not found: $input"
		return 2
	fi

	echo "<= $input"

	while [ $# -gt 1 ]
	do
		change="$( echo "$1" | tr '[:upper:]' '[:lower:]' )"

		case "$change" in
			169|43|60fps|audio|butter|crop219|crossfade|loop|mono|mp4|mute|reverse|rotate90|rotate180|rotate270|slowdown|twitter)
				output="$( _add_tag "$input" "$change" )"
				[ "$input" = "$output" ] && return
				[ -z "$final" ] && echo "=> $output" || echo "=> $change"
				"${scriptname}_${change}" > /dev/null 2>&1
				result=$?
				[ $result -gt 0 ] && return 3
				input="$output"
				;;

			*) return 4 ;;
		esac

		shift

		if [ $# -lt 2 ] && [ -n "$final" ]
		then
			mv "$output" "$final"
			echo "=> $final"
			rm -fr "$outputdir"
		fi
	done
}

vidmod_help() {
cat << USAGE
$scriptname $VERSION

USAGE: $scriptname [<options>] <change1> [<changen>...] <input>

Do rapid changes to video files using ffmpeg or other tools.

CHANGES:

	169, 43, 60fps, audio, butter, crop219, crossfade, loop, mono, mp4, mute,
	qt, reverse, rotate90, rotate180, rotate270, slowdown, twitter

OPTIONS:

	-d    Output directory. Defaults to directory of input file.
	-o    Last output file. When specified, any intermediate file will
	      be temporary.
	-h    Show this help screen.
	-v    Show version.

USAGE
}

vidmod_169() {
	# shellcheck disable=SC2086
	ffmpeg -i "$input" $ffmpeg_opts -vf "setdar=16/9" "$output"
}

vidmod_43() {
	# shellcheck disable=SC2086
	ffmpeg -i "$input" $ffmpeg_opts -vf "setdar=4/3" "$output"
}

vidmod_60fps() {
	# shellcheck disable=SC2086
	ffmpeg -i "$input" $ffmpeg_opts -r 60 "$output"
}

vidmod_audio() {
	# shellcheck disable=SC2086
	ffmpeg -i "$input" $ffmpeg_opts -vn -acodec copy "$output"
}

vidmod_butter() {
	butterflow "$input" -r 120 -audio --levels 6 -o "$output"
}

vidmod_crop219() {
	# shellcheck disable=SC2086
	ffmpeg -i "$input" $ffmpeg_opts -filter:v "crop=iw:iw/21*9" "$output"
}

vidmod_crossfade() {
	vidcrossfade -f 2 -o "$output" "$input"
}

vidmod_loop() {
	tmpfile="$( mktemp ".$scriptname.XXXXXX" )"

	for _ in 1 2
	do
		echo "file '$input'" >> "$tmpfile"
	done

	# shellcheck disable=SC2086
	ffmpeg -f concat -safe 0 -i "$tmpfile" $ffmpeg_opts \
		-c copy "$output"

	rm "$tmpfile"
}

vidmod_qt() {
	# shellcheck disable=SC2086
	ffmpeg \
		-i "$input" \
		-tag:v hvc1 -c:v copy -c:a copy -c:s mov_text \
		$ffmpeg_opts \
		"$output" \
	;
}

vidmod_mono() {
	# shellcheck disable=SC2086
	ffmpeg -i "$input" $ffmpeg_opts -ac 1 "$output"
}

vidmod_mp4() {
	# shellcheck disable=SC2086
	ffmpeg -i "$input" $ffmpeg_opts "$output"
}

vidmod_mute() {
	# shellcheck disable=SC2086
	ffmpeg -i "$input" $ffmpeg_opts -an -c copy "$output"
}

vidmod_reverse() {
	# shellcheck disable=SC2086
	ffmpeg -i "$input" $ffmpeg_opts -vf reverse -af areverse "$output"
}

vidmod_rotate90() {
	# shellcheck disable=SC2086
	ffmpeg -i "$input" $ffmpeg_opts -vf "transpose=1" "$output"
}

vidmod_rotate180() {
	# shellcheck disable=SC2086
	ffmpeg -i "$input" $ffmpeg_opts -vf "transpose=1,transpose=1" "$output"
}

vidmod_rotate270() {
	# shellcheck disable=SC2086
	ffmpeg -i "$input" $ffmpeg_opts -vf "transpose=2" "$output"
}

vidmod_slowdown() {
	# shellcheck disable=SC2086
	ffmpeg -i "$input" -filter:a "atempo=0.8" \
		$ffmpeg_opts \
		-filter:v "setpts=1.25*PTS" "$output"
}

vidmod_twitter() {
	# shellcheck disable=SC2086
	ffmpeg -i "$input" $ffmpeg_opts -vcodec libx264 \
		-vf 'scale=640:trunc(ow/a/2)*2' -acodec aac -vb 1024k -minrate 1024k \
		-maxrate 1024k -bufsize 1024k -ar 44100 -strict experimental -r 30 \
		"$output"
}

vidmod_version() {
	echo "$scriptname $VERSION"
}

_add_tag() {
	inpath="$1"
	tag="$2"

	inname="$( basename "$inpath" )"

	innoext="$( echo "$inname" | sed 's/\..*$//g' )"
	inext="$( echo "$inname" | grep -o '\..*$' )"

	case "$tag" in
		mp4|qt) echo "$outputdir/$innoext.mp4" ;;
		*) echo "$outputdir/$innoext-$tag$inext" ;;
	esac
}

_echo() {
	echo "$@"
}

_error() {
	_echo "$@" >&2
}

vidmod_main "$@"
